<?php
/**
 * TL_ROOT/system/modules/xtmembers/languages/de/default.php 
 * 
 * Contao extension: xtmembers 2.0.3 stable 
 * Deutsch translation file 
 * 
 * Copyright : &copy; Helmut Schottmüller 
 * License   : GNU Lesser Public License (LGPL) 
 * Author    : Helmut Schottmüller (hschottm), http://www.aurealis.de 
 * Translator: Helmut Schottmüller (hschottm), http://www.aurealis.de 
 * 
 * This file was created automatically be the Contao extension repository translation module.
 * Do not edit this file manually. Contact the author or translator for this module to establish 
 * permanent text corrections which are update-safe. 
 */
 
$GLOBALS['TL_LANG']['ERR']['agreement'] = "Bitte akzeptieren Sie die Nutzervereinbarung!";
 
?>
