<?php
/**
 * TL_ROOT/system/modules/xtmembers/languages/de/modules.php 
 * 
 * Contao extension: xtmembers 2.0.3 stable 
 * Deutsch translation file 
 * 
 * Copyright : &copy; Helmut Schottmüller 
 * License   : GNU Lesser Public License (LGPL) 
 * Author    : Helmut Schottmüller (hschottm), http://www.aurealis.de 
 * Translator: Helmut Schottmüller (hschottm), http://www.aurealis.de 
 * 
 * This file was created automatically be the Contao extension repository translation module.
 * Do not edit this file manually. Contact the author or translator for this module to establish 
 * permanent text corrections which are update-safe. 
 */
 
$GLOBALS['TL_LANG']['FMD']['memberpage']['0'] = "Mitgliederseite";
$GLOBALS['TL_LANG']['FMD']['memberpage']['1'] = "Dieses Modul zeigt die persönliche Seite eines Mitglieds an.";
$GLOBALS['TL_LANG']['FMD']['memberlist']['0'] = "Mitgliederliste";
$GLOBALS['TL_LANG']['FMD']['memberlist']['1'] = "Dieses Modul zeigt eine Liste von Mitgliedern ausgewählter Mitgliedergruppen an.";
$GLOBALS['TL_LANG']['FMD']['singlemember']['0'] = "Mitglieder-Details";
$GLOBALS['TL_LANG']['FMD']['singlemember']['1'] = "Dieses Modul zeigt die öffentlichen Details eines ausgewählten Mitglieds an.";
 
?>
