<?php
/**
 * TL_ROOT/system/modules/xtmembers/languages/de/tl_member_group.php 
 * 
 * Contao extension: xtmembers 2.0.3 stable 
 * Deutsch translation file 
 * 
 * Copyright : &copy; Helmut Schottmüller 
 * License   : GNU Lesser Public License (LGPL) 
 * Author    : Helmut Schottmüller (hschottm), http://www.aurealis.de 
 * Translator: Helmut Schottmüller (hschottm), http://www.aurealis.de 
 * 
 * This file was created automatically be the Contao extension repository translation module.
 * Do not edit this file manually. Contact the author or translator for this module to establish 
 * permanent text corrections which are update-safe. 
 */
 
$GLOBALS['TL_LANG']['tl_member_group']['disabledmemberfields']['0'] = "Deaktivierte Mitgliederfelder";
$GLOBALS['TL_LANG']['tl_member_group']['disabledmemberfields']['1'] = "Wählen Sie Mitgliederfelder aus, die für diese Mitgliedergruppe nicht verfügbar sein sollen.";
$GLOBALS['TL_LANG']['tl_member_group']['member_legend'] = "Mitgliedereinstellungen";
 
?>
