<?php
/**
 * TL_ROOT/system/modules/xtmembers/languages/de/tl_module.php 
 * 
 * Contao extension: xtmembers 2.0.3 stable 
 * Deutsch translation file 
 * 
 * Copyright : &copy; Helmut Schottmüller 
 * License   : GNU Lesser Public License (LGPL) 
 * Author    : Helmut Schottmüller (hschottm), http://www.aurealis.de 
 * Translator: Helmut Schottmüller (hschottm), http://www.aurealis.de 
 * 
 * This file was created automatically be the Contao extension repository translation module.
 * Do not edit this file manually. Contact the author or translator for this module to establish 
 * permanent text corrections which are update-safe. 
 */
 
$GLOBALS['TL_LANG']['tl_module']['member_template']['0'] = "Seitenvorlage";
$GLOBALS['TL_LANG']['tl_module']['member_template']['1'] = "Bitte wählen Sie ein Seitenlayout. Sie können eigene <em>memberpage_</em>-Vorlagen im Ordner <em>templates</em> speichern.";
$GLOBALS['TL_LANG']['tl_module']['memberlist_template']['0'] = "Listenvorlage";
$GLOBALS['TL_LANG']['tl_module']['memberlist_template']['1'] = "Bitte wählen Sie eine Listenvorlage. Sie können eigene <em>memberlist_</em>-Vorlagen im Ordner <em>templates</em> speichern.";
$GLOBALS['TL_LANG']['tl_module']['memberlist_fields']['0'] = "Sichtbare Felder";
$GLOBALS['TL_LANG']['tl_module']['memberlist_fields']['1'] = "Bitte wählen Sie mindestens ein Feld aus, das im Frontend sichtbar sein soll.";
$GLOBALS['TL_LANG']['tl_module']['singlemember']['0'] = "Mitglied";
$GLOBALS['TL_LANG']['tl_module']['singlemember']['1'] = "Bitte wählen Sie das Mitglied aus, dessen öffentliche Details angezeigt werden sollen.";
$GLOBALS['TL_LANG']['tl_module']['memberlist_show_searchfield']['0'] = "Suchfeld anzeigen";
$GLOBALS['TL_LANG']['tl_module']['memberlist_show_searchfield']['1'] = "Bitte geben Sie an, ob über der Mitgliederliste ein Suchfeld für Mitglieder angezeigt werden soll.";
$GLOBALS['TL_LANG']['tl_module']['show_member_name']['0'] = "Name des Mitglieds in Seitentitel anzeigen";
$GLOBALS['TL_LANG']['tl_module']['show_member_name']['1'] = "Zeit den jeweiligen Namen des Mitglieds bei Auswahl der Detailansicht im Seitentitel an.";
$GLOBALS['TL_LANG']['tl_module']['memberlist_showdetailscolumn']['0'] = "Zusätzliche Detailspalte";
$GLOBALS['TL_LANG']['tl_module']['memberlist_showdetailscolumn']['1'] = "Bitte wählen Sie, ob eine zusätzliche Detailspalte mit einem Link auf die Mitgliederdetails am Ende jeder Zeile angezeigt werden soll. Die Detailspalte wird nur angezeigt, wenn eine Weiterleitungsseite angegeben ist.";
$GLOBALS['TL_LANG']['tl_module']['memberlist_detailscolumn']['0'] = "Detailspalte";
$GLOBALS['TL_LANG']['tl_module']['memberlist_detailscolumn']['1'] = "Bitte Geben Sie den Feldnamen einer Spalte ein, die als Link zu den Mitgliederdetails verwendet werden soll. Der Spaltentext wird nur dann als Link angezeigt, wenn eine Weiterleitungsseite angegeben ist.";
$GLOBALS['TL_LANG']['tl_module']['registration_show_agreement']['0'] = "Nutzervereinbarung anzeigen";
$GLOBALS['TL_LANG']['tl_module']['registration_show_agreement']['1'] = "Wählen Sie aus, ob bei der Registrierung eine Nutzervereinbarung angezeigt werden soll. Die Registrierung kann dann nur durch Akzeptieren der Nutzervereinbarung abgeschlossen werden.";
$GLOBALS['TL_LANG']['tl_module']['registration_agreement_text']['0'] = "Nutzervereinbarung";
$GLOBALS['TL_LANG']['tl_module']['registration_agreement_text']['1'] = "Geben Sie hier den Text für die Nutzervereinbarung ein. Dieser Text wird dann bei der Registrierung angezeigt.";
$GLOBALS['TL_LANG']['tl_module']['registration_agreement_headline']['0'] = "Aufforderung zur Nutzervereinbarung";
$GLOBALS['TL_LANG']['tl_module']['registration_agreement_headline']['1'] = "Geben Sie hier den Hinweistext ein, der dazu auffordern soll, die Nutzervereinbarung zu akzeptieren.";
$GLOBALS['TL_LANG']['tl_module']['registration_allow_groupselection']['0'] = "Gruppenauswahl ermöglichen";
$GLOBALS['TL_LANG']['tl_module']['registration_allow_groupselection']['1'] = "Wählen Sie aus, ob bei der Registrierung eine vorhandene Mitgliedsgruppe ausgewählt werden soll.";
$GLOBALS['TL_LANG']['tl_module']['registration_groupselection_groups']['0'] = "Verfügbare Gruppen";
$GLOBALS['TL_LANG']['tl_module']['registration_groupselection_groups']['1'] = "Wählen Sie die Gruppen, die während der Registrierung zur Auswahl stehen sollen.";
$GLOBALS['TL_LANG']['tl_module']['personaldata_page_editor']['0'] = "Seiteneditor aktivieren";
$GLOBALS['TL_LANG']['tl_module']['personaldata_page_editor']['1'] = "Wählen Sie aus, ob die Mitglieder ihre Mitgliedsseiten mit Hilfe eines Seiteneditors erweitern können.";
$GLOBALS['TL_LANG']['tl_module']['reg_select_group'] = "-- Nutzergruppe auswählen --";
$GLOBALS['TL_LANG']['tl_module']['new_page'] = "Neue Seite";
$GLOBALS['TL_LANG']['tl_module']['content'] = "Inhalt";
$GLOBALS['TL_LANG']['tl_module']['pageTitle'] = "Seitentitel";
$GLOBALS['TL_LANG']['tl_module']['deletePage'] = "Seite löschen";
$GLOBALS['TL_LANG']['tl_module']['add'] = "Hinzufügen";
$GLOBALS['TL_LANG']['tl_module']['about_person'] = "Zur Person";
$GLOBALS['TL_LANG']['tl_module']['confirmDeletePage'] = "Sind Sie sicher, dass Sie die aktuelle Seite löschen wollen?";
$GLOBALS['TL_LANG']['tl_module']['pagetype']['essay'] = "Text";
$GLOBALS['TL_LANG']['tl_module']['memberlist_where']['0'] = "Bedingung";
$GLOBALS['TL_LANG']['tl_module']['memberlist_where']['1'] = "Hier können Sie eine Bedingung eingeben, um die Ergebnisse zu filtern (z.B. <em>locked=1</em> oder <em>lastname!=\"Müller\"</em>).";
$GLOBALS['TL_LANG']['tl_module']['pageeditor_legend'] = "Seiteneditor";
$GLOBALS['TL_LANG']['tl_module']['agreement_legend'] = "Nutzervereinbarung";
$GLOBALS['TL_LANG']['tl_module']['groupselection_legend'] = "Gruppenauswahl";
 
?>
