<?php
/**
 * TL_ROOT/system/modules/xtmembers/languages/de/tl_member.php 
 * 
 * Contao extension: xtmembers 2.0.3 stable 
 * Deutsch translation file 
 * 
 * Copyright : &copy; Helmut Schottmüller 
 * License   : GNU Lesser Public License (LGPL) 
 * Author    : Helmut Schottmüller (hschottm), http://www.aurealis.de 
 * Translator: Helmut Schottmüller (hschottm), http://www.aurealis.de 
 * 
 * This file was created automatically be the Contao extension repository translation module.
 * Do not edit this file manually. Contact the author or translator for this module to establish 
 * permanent text corrections which are update-safe. 
 */
 
$GLOBALS['TL_LANG']['tl_member']['title']['0'] = "Titel";
$GLOBALS['TL_LANG']['tl_member']['title']['1'] = "Bitte geben Sie den Titel/akademischen Grad ein.";
$GLOBALS['TL_LANG']['tl_member']['title_extended']['0'] = "Titel (erweitert)";
$GLOBALS['TL_LANG']['tl_member']['title_extended']['1'] = "Bitte geben Sie einen erweiterten Titel/akademischen Grad ein.";
$GLOBALS['TL_LANG']['tl_member']['salutation']['0'] = "Anrede";
$GLOBALS['TL_LANG']['tl_member']['salutation']['1'] = "Bitte geben Sie die Anrede (z.B. Frau, Herr etc.) ein.";
$GLOBALS['TL_LANG']['tl_member']['branch']['0'] = "Branche";
$GLOBALS['TL_LANG']['tl_member']['branch']['1'] = "Bitte geben Sie die Branche ein.";
$GLOBALS['TL_LANG']['tl_member']['business_connection']['0'] = "Art der Geschäfsbeziehung";
$GLOBALS['TL_LANG']['tl_member']['business_connection']['1'] = "Bitte geben Sie die Art der Geschäftsbeziehung ein.";
$GLOBALS['TL_LANG']['tl_member']['campaign']['0'] = "Kampagne";
$GLOBALS['TL_LANG']['tl_member']['campaign']['1'] = "Bitte geben Sie eine Kampagne ein.";
$GLOBALS['TL_LANG']['tl_member']['jobtitle']['0'] = "Jobtitel";
$GLOBALS['TL_LANG']['tl_member']['jobtitle']['1'] = "Bitte geben Sie den Jobtitel ein.";
$GLOBALS['TL_LANG']['tl_member']['jobtitle_bc']['0'] = "Jobtitel (Visitenkarte)";
$GLOBALS['TL_LANG']['tl_member']['jobtitle_bc']['1'] = "Bitte geben Sie den Jobtitel der Visitenkarte ein.";
$GLOBALS['TL_LANG']['tl_member']['description']['0'] = "Beschreibung der Position";
$GLOBALS['TL_LANG']['tl_member']['description']['1'] = "Bitte geben Sie eine alternative Beschreibung Ihrer Position ein.";
$GLOBALS['TL_LANG']['tl_member']['notes']['0'] = "Notizen";
$GLOBALS['TL_LANG']['tl_member']['notes']['1'] = "Bitte geben Sie Ihre Notizen ein.";
$GLOBALS['TL_LANG']['tl_member']['company']['0'] = "Institution";
$GLOBALS['TL_LANG']['tl_member']['company']['1'] = "Bitte geben Sie eine Institution/Firma ein.";
$GLOBALS['TL_LANG']['tl_member']['officehours']['0'] = "Sprechstunde";
$GLOBALS['TL_LANG']['tl_member']['officehours']['1'] = "Bitte geben Sie Sprechstundenzeiten ein.";
$GLOBALS['TL_LANG']['tl_member']['street']['0'] = "Adresszeile 1";
$GLOBALS['TL_LANG']['tl_member']['street']['1'] = "Bitte geben Sie eine Adresszeile der Adresse ein.";
$GLOBALS['TL_LANG']['tl_member']['address2']['0'] = "Adresszeile 2";
$GLOBALS['TL_LANG']['tl_member']['address2']['1'] = "Bitte geben Sie eine Adresszeile der Adresse ein.";
$GLOBALS['TL_LANG']['tl_member']['room']['0'] = "Raumnummer";
$GLOBALS['TL_LANG']['tl_member']['room']['1'] = "Bitte geben Sie eine Raumnummer ein.";
$GLOBALS['TL_LANG']['tl_member']['department']['0'] = "Abteilung";
$GLOBALS['TL_LANG']['tl_member']['department']['1'] = "Bitte geben Sie eine Abteilung/Organisationseinheit ein.";
$GLOBALS['TL_LANG']['tl_member']['building']['0'] = "Gebäude";
$GLOBALS['TL_LANG']['tl_member']['building']['1'] = "Bitte geben Sie eine Gebäudenummer oder Gebäudebezeichnung ein.";
$GLOBALS['TL_LANG']['tl_member']['joined']['0'] = "Arbeitsbeginn";
$GLOBALS['TL_LANG']['tl_member']['joined']['1'] = "Bitte geben Sie ein Datum für den Beginn der Arbeitstätigkeit ein.";
$GLOBALS['TL_LANG']['tl_member']['resigned']['0'] = "Ausgeschieden";
$GLOBALS['TL_LANG']['tl_member']['resigned']['1'] = "Bitte geben Sie ein Datum für den Termin des Ausscheidens ein.";
$GLOBALS['TL_LANG']['tl_member']['workscope']['0'] = "Arbeitsgebiet";
$GLOBALS['TL_LANG']['tl_member']['workscope']['1'] = "Bitte geben Sie eine Beschreibung für das Arbeits- und Aufgabengebiet ein.";
$GLOBALS['TL_LANG']['tl_member']['postaladdress'] = "Postanschrift";
$GLOBALS['TL_LANG']['tl_member']['name'] = "Name";
$GLOBALS['TL_LANG']['tl_member']['agreement'] = "Nutzervereinbarung";
$GLOBALS['TL_LANG']['tl_member']['accept_agreement'] = 'Akzeptieren';
$GLOBALS['TL_LANG']['tl_member']['pageVisible']['0'] = "Die Seite ist sichtbar";
$GLOBALS['TL_LANG']['tl_member']['pageVisible']['1'] = "Wählen Sie aus, ob diese Seite für alle sichtbar sein soll.";
$GLOBALS['TL_LANG']['tl_member']['dateAdded']['0'] = "Hinzugefügt am";
$GLOBALS['TL_LANG']['tl_member']['dateAdded']['1'] = "Datum, an dem das Mitglied hinzugefügt wurde";
$GLOBALS['TL_LANG']['tl_member']['work_legend'] = "Arbeitsbeschreibungen";
$GLOBALS['TL_LANG']['tl_member']['customer_legend'] = "Kundenbeziehungen";

?>
