<?php
/**
 * TL_ROOT/system/modules/xtmembers/languages/de/tl_settings.php 
 * 
 * Contao extension: xtmembers 2.0.3 stable 
 * Deutsch translation file 
 * 
 * Copyright : &copy; Helmut Schottmüller 
 * License   : GNU Lesser Public License (LGPL) 
 * Author    : Helmut Schottmüller (hschottm), http://www.aurealis.de 
 * Translator: Helmut Schottmüller (hschottm), http://www.aurealis.de 
 * 
 * This file was created automatically be the Contao extension repository translation module.
 * Do not edit this file manually. Contact the author or translator for this module to establish 
 * permanent text corrections which are update-safe. 
 */
 
$GLOBALS['TL_LANG']['tl_settings']['inactivememberfields']['0'] = "Inaktive Mitgliedsfelder";
$GLOBALS['TL_LANG']['tl_settings']['inactivememberfields']['1'] = "Hier können Sie nicht benötigte Benutzerfelder deaktivieren.";
$GLOBALS['TL_LANG']['tl_settings']['memberurlparameter']['0'] = "URL-Parameter für Mitgliedsseiten-Aufrufe";
$GLOBALS['TL_LANG']['tl_settings']['memberurlparameter']['1'] = "Geben Sie den Namen des URL-Parameters für Mitgliedsseitenaufrufe an. Der URL-Parameter enthält die ID der aufzurufenden Mitgliedsseite, z.B. http://PFAD_ZUR_MITGLIEDSSEITE?member=ID. In diesem Beispiel ist der Name des URL-Parameters <strong>member</strong>.";
$GLOBALS['TL_LANG']['tl_settings']['member_legend'] = "Mitgliedereinstellungen";
 
?>
